### ISSUE TITLE
Crossbow doesn't work correctly

### ISSUE THREAD

**Issue by ConnorArc** [ToBinio/real-arrow-tip#3]
Crossbow doesn't work if there just one arrow tip or spectral in inventory: https://imgur.com/crossbow-bug-HyYfNOr

**Comment by ToBinio** [comment]
Thanks for reporting!
it was caused by an oversight, i set the color based on the arrow which would be chosen as the next one

**Comment by ConnorArc** [comment]
oh got it, this mod is very cool thx man

**Comment by ToBinio** [comment]
fixed
just reuploaded 0.1.1 with the additional fix - nobody will know 🤫

thanks again!

**Comment by ConnorArc** [comment]
haha yeah 🤫
